version: '3'

services:
  geth:
    image: ethereum/client-go:v1.8.22
    volumes:
      - /home/ubuntu/:/geth
    command: "--cache 2048 --syncmode 'fast' --maxpeers 50 --datadir geth/.ethereum  --rpcapi admin,debug,miner,shh,txpool,personal,eth,net,web3 --rpc --rpcvhosts=* --ethstats=node:YWRzZm1md29lbmlvMjMxMjEyMg==@ethstats:3000 --verbosity=4"
    restart: on-failure
    networks:
      - project
    ports:
      - 30303:30303
      - 30303:30303/udp

  healthchecker:
    build:
      context: .
      dockerfile: docker/healthchecker/Dockerfile
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - ./:/app
      - /app/health-checker/node_modules
    networks:
      - project
    env_file:
      - health-checker/envs/prod.env

networks:
  project:
