version: '3'

services:
  geth:
    image: ethereum/client-go:v1.8.22
    volumes:
      - {ETHEREUM_DIR}:/geth/.ethereum
    command: "--cache 4096 --syncmode 'fast' --maxpeers 30 --datadir geth/.ethereum  --rpcapi admin,debug,miner,shh,txpool,personal,eth,net,web3 --rpc --rpcvhosts=* --rpcaddr 0.0.0.0 --ethstats={NODE_UNIQUE_NAME}:{ETHSTATS_SECRET}@{ETHSTATS_HOST}:3000 --verbosity=4"
    restart: on-failure
    networks:
      - project
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546

  healthchecker:
    build:
      context: .
      dockerfile: docker/healthchecker/Dockerfile
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - ./:/app
      - /app/health-checker/node_modules
    networks:
      - project
    env_file:
      - health-checker/envs/prod.env

networks:
  project:
